### ISSUE TITLE
UE4.26 android package

### ISSUE THREAD

**Issue by mspcbs** [getnamo/BLUI#58] opened 2021-02-24 16:20 UTC
UE4.26 after package(android) my project HTML is not working(is not shown) .  but it's working in project viewport launch

**Comment by getnamo** [comment] 2021-02-26 17:33
Duplicate of https://github.com/getnamo/BLUI/issues/24.

Android support depends on CEF/chromium library build for android being available, which atm I'm not aware of it being easily available.

**Closed by getnamo** 2021-02-26 17:33 UTC
Labels: duplicate
